steps:

# Copy id_rsa.enc, known_hosts ... from buck
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://$BUCKET_NAME/*', '.']

# Decrypt the file containing the key
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=$KEYRING_NAME
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
    git submodule sync
    git submodule init
    git submodule update
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
#    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:builder',
#    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.'
  ]

#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build',
#         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', 
#         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
#         '-f', 'Dockerfile.slim',
#         '.'
#  ]
#- name: 'gcr.io/cloud-builders/docker'
#  args: [
#            'build',
#            '-t', 'gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest',
#            '--cache-from', 'gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest',
#            '.'
#        ]
#images: ['gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest']

images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
  'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
]

substitutions:
    BUCKET_NAME: htc-net-vn-common-bucket
    KEYRING_NAME: htc-net-vn-common-keyring
