steps:

# Copy key
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://vuminhtuan_fit_bucket/id_rsa.enc', 'id_rsa.enc']

# Copy key
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://vuminhtuan_fit_bucket/known_hosts', 'known_hosts']

# Decrypt the file containing the key
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=my-keyring
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
    git submodule sync
    git submodule init
    git submodule update
    git submodule foreach git checkout master
    git submodule foreach git pull origin master
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Checkout modules
#- name: 'gcr.io/cloud-builders/git'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    git submodule sync && \
#    git submodule init && \
#    git submodule update && \
#    git submodule foreach git checkout master && \
#    git submodule foreach git pull origin master
#  volumes:
#  - name: 'ssh'
#    path: /root/.ssh
#- name: 'gcr.io/cloud-builders/git'
#  args: ['submodule', 'init']
#  volumes:
#  - name: 'ssh'
#    path: /root/.ssh
#- name: 'gcr.io/cloud-builders/git'
#  args: ['submodule', 'update']
#  volumes:
#  - name: 'ssh'
#    path: /root/.ssh
#- name: 'gcr.io/cloud-builders/git'
#  args: ['submodule', 'foreach', 'git', 'checkout', $BRANCH_NAME]
#  volumes:
#  - name: 'ssh'
#    path: /root/.ssh
#- name: 'gcr.io/cloud-builders/git'
#  args: ['submodule', 'foreach', 'git', 'pull', 'origin', $BRANCH_NAME]
#  volumes:
#  - name: 'ssh'
#    path: /root/.ssh

#- name: 'gcr.io/cloud-builders/docker'
#  entrypoint: 'bash'
#  args: [
#    '-c',
#    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME:builder || true']
#
#- name: 'gcr.io/cloud-builders/docker'
#  entrypoint: 'bash'
#  args: [
#    '-c',
#    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME:latest || true']
#
#- name: 'gcr.io/cloud-builders/docker'
#  args: [
#    'build',
#    '--target', 'builder',
#    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:builder',
#    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:builder',
#    '.']
#
#- name: 'gcr.io/cloud-builders/docker'
#  args: [
#    'build',
#    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
#    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
#    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:builder',
#    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
#    '.']
#
#images: [
#  'gcr.io/$PROJECT_ID/$REPO_NAME:builder',
#  'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
#  'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']




#- name: 'gcr.io/cloud-builders/docker'
#  args: [
#    'build',
#    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
#    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
#    '.']
#
#images: [
#  'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
#  'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']


- name: 'openjdk:8'
  entrypoint: "bash"
  # args: [ "-c", "./gradlew --no-daemon -x test npm-build build"]
  # args: [ "-c", "./gradlew --no-daemon -x test build"]
  args: [ "-c", "./gradlew --no-daemon -x copyWebapp"]

- name: node:10.10.0
  entrypoint: npm
  args: ['install --prefix ./build/webapp']

- name: node:10.10.0
  entrypoint: npm
  args: ['run build ./build/webapp']

- name: 'openjdk:8'
  entrypoint: "bash"
  # args: [ "-c", "./gradlew --no-daemon -x test npm-build build"]
  args: [ "-c", "./gradlew --no-daemon -x test build"]
  
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build',
#         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
#         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
#         '-f', 'Dockerfile', '.'
#  ]
# images:
# - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
# - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'

# Use git clone.
# - name: 'gcr.io/cloud-builders/git'
  # args:
  # - clone
  # - git@github.com:[GIT-USERNAME]/[REPOSITORY]
  # - git@github.com:minhtuanvu/abs-webapp.git
  # volumes:
  # - name: 'ssh'
    # path: /root/.ssh
